language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

src_files:
    - hello.js
    - hello_spec.js

launchers:
    CI:
        command: mocha --timeout 3000 hello_spec.js -R tap
        protocol: tap
launch_in_ci:
    - CI